### ISSUE TITLE
Invalid App package. Could not find the classFile (YouTrackChargerApp.js) file

### ISSUE THREAD

**Issue by bulkinav** [igorich/YouTrackCharger#3]
@igorich thanks for this module, but I can't install it via <rocket.chat>/admin/marketplace/all/install - when I press Install butoon and then Agree permissions button, the following POST request are sending:

---
Request URL: https://chat.ottmedia.ru/api/apps
Payload:
app: (binary)
permissions: undefined

Request Method: POST
Status Code: 400 Bad Request

```
error:  "Invalid App package. Could not find the classFile (YouTrackChargerApp.js) file."
success: false
```
---

Rocket.Chat Server 5.4.1

**Comment by igorich** [comment]
got it.
I will take a look soon and let you know.

**Comment by igorich** [comment]
@bulkinav  can you post your compiled app here?
We have YouTrackCharger app successfully installed on our server ver 5.4.0

**Comment by bulkinav** [comment]
@igorich I cloned the repo and then trying upload it to Rocke.Chat. The archive example: https://disk.yandex.ru/d/83VjJozrfzU-nQ

**Comment by igorich** [comment]
did you compiled sources to app with `rc-apps` tool?

UPD just execute `rc-apps package` in root folder of app sources, and look for package in ./dist/ directory

how to install Rocket CLI
https://github.com/RocketChat/Rocket.Chat.Apps-cli

**Comment by bulkinav** [comment]
Ok, this is my mistake. It's just that I've never upload custom apps before.

But now the following error appear after 'package' command:

```
packaging your app... !
 ›   Error: Error YouTrackChargerApp.ts (39,17): Type 'WebhookEndpoint' is not assignable to type 'IApiEndpoint'.
 ›     undefined
```

node -v
v19.2.0

Maybe it will be easier if you share the application package for me?

**Comment by igorich** [comment]
sure, no problem
[youtrackcharger_0.1.1.zip](https://github.com/igorich/YouTrackCharger/files/10317547/youtrackcharger_0.1.1.zip)
